/*
    This file was automatically generated by Studio 3T.

    MongoDB Source Collection: `ekspor_impor.ekspor`

    Warnings about type conversion issues are stored as comments above the
    corresponding INSERT statement of each document.
*/


SET NAMES 'utf8' COLLATE 'utf8_general_ci';

DROP TABLE IF EXISTS `ekspor`;
CREATE TABLE `ekspor` (
    `Berat/Weight (KG)` DOUBLE,
    `Bulan/Month` LONGTEXT,
    `Nilai/Value (US $)` DOUBLE,
    `Tahun` INTEGER
) CHARSET=utf8;

INSERT INTO `ekspor` (`Berat/Weight (KG)`, `Bulan/Month`, `Nilai/Value (US $)`, `Tahun`)
    VALUES
        (4.3728031415E10, 'Januari/January', 1.159586712E10, 2010);
INSERT INTO `ekspor` (`Berat/Weight (KG)`, `Bulan/Month`, `Nilai/Value (US $)`, `Tahun`)
    VALUES
        (3.4365506564E10, 'Pebruari/February', 1.1166450436E10, 2010);
INSERT INTO `ekspor` (`Berat/Weight (KG)`, `Bulan/Month`, `Nilai/Value (US $)`, `Tahun`)
    VALUES
        (4.2805393284E10, 'Maret/March', 1.2774365884E10, 2010);
INSERT INTO `ekspor` (`Berat/Weight (KG)`, `Bulan/Month`, `Nilai/Value (US $)`, `Tahun`)
    VALUES
        (3.7246261411E10, 'April/April', 1.2035247591E10, 2010);
INSERT INTO `ekspor` (`Berat/Weight (KG)`, `Bulan/Month`, `Nilai/Value (US $)`, `Tahun`)
    VALUES
        (3.9517382367E10, 'Mei/May', 1.2619125277E10, 2010);
INSERT INTO `ekspor` (`Berat/Weight (KG)`, `Bulan/Month`, `Nilai/Value (US $)`, `Tahun`)
    VALUES
        (3.9882450381E10, 'Juni/June', 1.2330114499E10, 2010);
INSERT INTO `ekspor` (`Berat/Weight (KG)`, `Bulan/Month`, `Nilai/Value (US $)`, `Tahun`)
    VALUES
        (3.6176018308E10, 'Juli/July', 1.2486972905E10, 2010);
INSERT INTO `ekspor` (`Berat/Weight (KG)`, `Bulan/Month`, `Nilai/Value (US $)`, `Tahun`)
    VALUES
        (3.9589239893E10, 'Agustus/August', 1.3726521968E10, 2010);
INSERT INTO `ekspor` (`Berat/Weight (KG)`, `Bulan/Month`, `Nilai/Value (US $)`, `Tahun`)
    VALUES
        (3.3193394348E10, 'September/September', 1.2181628292E10, 2010);
INSERT INTO `ekspor` (`Berat/Weight (KG)`, `Bulan/Month`, `Nilai/Value (US $)`, `Tahun`)
    VALUES
        (3.7582744074E10, 'Oktober/October', 1.4399644857E10, 2010);
INSERT INTO `ekspor` (`Berat/Weight (KG)`, `Bulan/Month`, `Nilai/Value (US $)`, `Tahun`)
    VALUES
        (4.7750908307E10, 'Nopember/November', 1.5633275868E10, 2010);
INSERT INTO `ekspor` (`Berat/Weight (KG)`, `Bulan/Month`, `Nilai/Value (US $)`, `Tahun`)
    VALUES
        (4.700946728E10, 'Desember/December', 1.6829888773E10, 2010);
INSERT INTO `ekspor` (`Berat/Weight (KG)`, `Bulan/Month`, `Nilai/Value (US $)`, `Tahun`)
    VALUES
        (4.3079006755E10, 'Januari/January', 1.4606249454E10, 2011);
INSERT INTO `ekspor` (`Berat/Weight (KG)`, `Bulan/Month`, `Nilai/Value (US $)`, `Tahun`)
    VALUES
        (3.9675423843E10, 'Pebruari/February', 1.4415278398E10, 2011);
INSERT INTO `ekspor` (`Berat/Weight (KG)`, `Bulan/Month`, `Nilai/Value (US $)`, `Tahun`)
    VALUES
        (4.3300354495E10, 'Maret/March', 1.6365953469E10, 2011);
INSERT INTO `ekspor` (`Berat/Weight (KG)`, `Bulan/Month`, `Nilai/Value (US $)`, `Tahun`)
    VALUES
        (4.2104466228E10, 'April/April', 1.6554240767E10, 2011);
INSERT INTO `ekspor` (`Berat/Weight (KG)`, `Bulan/Month`, `Nilai/Value (US $)`, `Tahun`)
    VALUES
        (5.2298466219E10, 'Mei/May', 1.8287435825E10, 2011);
INSERT INTO `ekspor` (`Berat/Weight (KG)`, `Bulan/Month`, `Nilai/Value (US $)`, `Tahun`)
    VALUES
        (5.0341916416E10, 'Juni/June', 1.8386855403E10, 2011);
INSERT INTO `ekspor` (`Berat/Weight (KG)`, `Bulan/Month`, `Nilai/Value (US $)`, `Tahun`)
    VALUES
        (5.0468063649E10, 'Juli/July', 1.7418472565E10, 2011);
INSERT INTO `ekspor` (`Berat/Weight (KG)`, `Bulan/Month`, `Nilai/Value (US $)`, `Tahun`)
    VALUES
        (4.8729818148E10, 'Agustus/August', 1.8647825151E10, 2011);
INSERT INTO `ekspor` (`Berat/Weight (KG)`, `Bulan/Month`, `Nilai/Value (US $)`, `Tahun`)
    VALUES
        (4.9677982009E10, 'September/September', 1.7543408243E10, 2011);
INSERT INTO `ekspor` (`Berat/Weight (KG)`, `Bulan/Month`, `Nilai/Value (US $)`, `Tahun`)
    VALUES
        (5.2558546328E10, 'Oktober/October', 1.6957743283E10, 2011);
INSERT INTO `ekspor` (`Berat/Weight (KG)`, `Bulan/Month`, `Nilai/Value (US $)`, `Tahun`)
    VALUES
        (5.5859996898E10, 'Nopember/November', 1.7235463273E10, 2011);
INSERT INTO `ekspor` (`Berat/Weight (KG)`, `Bulan/Month`, `Nilai/Value (US $)`, `Tahun`)
    VALUES
        (5.4125738295E10, 'Desember/December', 1.7077694229E10, 2011);
INSERT INTO `ekspor` (`Berat/Weight (KG)`, `Bulan/Month`, `Nilai/Value (US $)`, `Tahun`)
    VALUES
        (4.611105069E10, 'Januari/January', 1.557006932E10, 2012);
INSERT INTO `ekspor` (`Berat/Weight (KG)`, `Bulan/Month`, `Nilai/Value (US $)`, `Tahun`)
    VALUES
        (4.680934435E10, 'Pebruari/February', 1.5695443242E10, 2012);
INSERT INTO `ekspor` (`Berat/Weight (KG)`, `Bulan/Month`, `Nilai/Value (US $)`, `Tahun`)
    VALUES
        (5.6650974567E10, 'Maret/March', 1.7251519437E10, 2012);
INSERT INTO `ekspor` (`Berat/Weight (KG)`, `Bulan/Month`, `Nilai/Value (US $)`, `Tahun`)
    VALUES
        (5.6984747251E10, 'April/April', 1.6173190978E10, 2012);
INSERT INTO `ekspor` (`Berat/Weight (KG)`, `Bulan/Month`, `Nilai/Value (US $)`, `Tahun`)
    VALUES
        (5.0037143958E10, 'Mei/May', 1.682954555E10, 2012);
INSERT INTO `ekspor` (`Berat/Weight (KG)`, `Bulan/Month`, `Nilai/Value (US $)`, `Tahun`)
    VALUES
        (4.2563479244E10, 'Juni/June', 1.5441457938E10, 2012);
INSERT INTO `ekspor` (`Berat/Weight (KG)`, `Bulan/Month`, `Nilai/Value (US $)`, `Tahun`)
    VALUES
        (4.2089792231E10, 'Juli/July', 1.6090595299E10, 2012);
INSERT INTO `ekspor` (`Berat/Weight (KG)`, `Bulan/Month`, `Nilai/Value (US $)`, `Tahun`)
    VALUES
        (4.187636372E10, 'Agustus/August', 1.4047007385E10, 2012);
INSERT INTO `ekspor` (`Berat/Weight (KG)`, `Bulan/Month`, `Nilai/Value (US $)`, `Tahun`)
    VALUES
        (4.528103694E10, 'September/September', 1.5898115717E10, 2012);
INSERT INTO `ekspor` (`Berat/Weight (KG)`, `Bulan/Month`, `Nilai/Value (US $)`, `Tahun`)
    VALUES
        (5.2612600648E10, 'Oktober/October', 1.5324042715E10, 2012);
INSERT INTO `ekspor` (`Berat/Weight (KG)`, `Bulan/Month`, `Nilai/Value (US $)`, `Tahun`)
    VALUES
        (5.9388239071E10, 'Nopember/November', 1.6316911273E10, 2012);
INSERT INTO `ekspor` (`Berat/Weight (KG)`, `Bulan/Month`, `Nilai/Value (US $)`, `Tahun`)
    VALUES
        (5.973257428E10, 'Desember/December', 1.539394639E10, 2012);
INSERT INTO `ekspor` (`Berat/Weight (KG)`, `Bulan/Month`, `Nilai/Value (US $)`, `Tahun`)
    VALUES
        (5.5661972692E10, 'Januari/January', 1.5375487902E10, 2013);
INSERT INTO `ekspor` (`Berat/Weight (KG)`, `Bulan/Month`, `Nilai/Value (US $)`, `Tahun`)
    VALUES
        (5.3861770156E10, 'Pebruari/February', 1.5015627735E10, 2013);
INSERT INTO `ekspor` (`Berat/Weight (KG)`, `Bulan/Month`, `Nilai/Value (US $)`, `Tahun`)
    VALUES
        (5.977650921E10, 'Maret/March', 1.5024577683E10, 2013);
INSERT INTO `ekspor` (`Berat/Weight (KG)`, `Bulan/Month`, `Nilai/Value (US $)`, `Tahun`)
    VALUES
        (5.8887635554E10, 'April/April', 1.4760892129E10, 2013);
INSERT INTO `ekspor` (`Berat/Weight (KG)`, `Bulan/Month`, `Nilai/Value (US $)`, `Tahun`)
    VALUES
        (6.1440502451E10, 'Mei/May', 1.6133358194E10, 2013);
INSERT INTO `ekspor` (`Berat/Weight (KG)`, `Bulan/Month`, `Nilai/Value (US $)`, `Tahun`)
    VALUES
        (5.4121878206E10, 'Juni/June', 1.4758819151E10, 2013);
INSERT INTO `ekspor` (`Berat/Weight (KG)`, `Bulan/Month`, `Nilai/Value (US $)`, `Tahun`)
    VALUES
        (5.6083727696E10, 'Juli/July', 1.5087863565E10, 2013);
INSERT INTO `ekspor` (`Berat/Weight (KG)`, `Bulan/Month`, `Nilai/Value (US $)`, `Tahun`)
    VALUES
        (5.3046541725E10, 'Agustus/August', 1.3083711035E10, 2013);
INSERT INTO `ekspor` (`Berat/Weight (KG)`, `Bulan/Month`, `Nilai/Value (US $)`, `Tahun`)
    VALUES
        (5.5867989989E10, 'September/September', 1.470677508E10, 2013);
INSERT INTO `ekspor` (`Berat/Weight (KG)`, `Bulan/Month`, `Nilai/Value (US $)`, `Tahun`)
    VALUES
        (5.7019945829E10, 'Oktober/October', 1.5698330394E10, 2013);
INSERT INTO `ekspor` (`Berat/Weight (KG)`, `Bulan/Month`, `Nilai/Value (US $)`, `Tahun`)
    VALUES
        (6.5039844044E10, 'Nopember/November', 1.5938557641E10, 2013);
INSERT INTO `ekspor` (`Berat/Weight (KG)`, `Bulan/Month`, `Nilai/Value (US $)`, `Tahun`)
    VALUES
        (6.9196719738E10, 'Desember/December', 1.6967798188E10, 2013);
INSERT INTO `ekspor` (`Berat/Weight (KG)`, `Bulan/Month`, `Nilai/Value (US $)`, `Tahun`)
    VALUES
        (4.9154384703E10, 'Januari/January', 1.4472289332E10, 2014);
INSERT INTO `ekspor` (`Berat/Weight (KG)`, `Bulan/Month`, `Nilai/Value (US $)`, `Tahun`)
    VALUES
        (4.3416241019E10, 'Pebruari/February', 1.463409039E10, 2014);
INSERT INTO `ekspor` (`Berat/Weight (KG)`, `Bulan/Month`, `Nilai/Value (US $)`, `Tahun`)
    VALUES
        (4.9294958689E10, 'Maret/March', 1.5192634701E10, 2014);
INSERT INTO `ekspor` (`Berat/Weight (KG)`, `Bulan/Month`, `Nilai/Value (US $)`, `Tahun`)
    VALUES
        (4.5541731344E10, 'April/April', 1.4292472554E10, 2014);
INSERT INTO `ekspor` (`Berat/Weight (KG)`, `Bulan/Month`, `Nilai/Value (US $)`, `Tahun`)
    VALUES
        (4.7417633575E10, 'Mei/May', 1.4823602661E10, 2014);
INSERT INTO `ekspor` (`Berat/Weight (KG)`, `Bulan/Month`, `Nilai/Value (US $)`, `Tahun`)
    VALUES
        (4.4989016798E10, 'Juni/June', 1.5409451765E10, 2014);
INSERT INTO `ekspor` (`Berat/Weight (KG)`, `Bulan/Month`, `Nilai/Value (US $)`, `Tahun`)
    VALUES
        (4.3624537982E10, 'Juli/July', 1.4124129298E10, 2014);
INSERT INTO `ekspor` (`Berat/Weight (KG)`, `Bulan/Month`, `Nilai/Value (US $)`, `Tahun`)
    VALUES
        (4.3484947226E10, 'Agustus/August', 1.4481642319E10, 2014);
INSERT INTO `ekspor` (`Berat/Weight (KG)`, `Bulan/Month`, `Nilai/Value (US $)`, `Tahun`)
    VALUES
        (4.6043270707E10, 'September/September', 1.5275846089E10, 2014);
INSERT INTO `ekspor` (`Berat/Weight (KG)`, `Bulan/Month`, `Nilai/Value (US $)`, `Tahun`)
    VALUES
        (4.3705129574E10, 'Oktober/October', 1.529275901E10, 2014);
INSERT INTO `ekspor` (`Berat/Weight (KG)`, `Bulan/Month`, `Nilai/Value (US $)`, `Tahun`)
    VALUES
        (4.6182204245E10, 'Nopember/November', 1.3544729209E10, 2014);
INSERT INTO `ekspor` (`Berat/Weight (KG)`, `Bulan/Month`, `Nilai/Value (US $)`, `Tahun`)
    VALUES
        (4.661139561E10, 'Desember/December', 1.443633966E10, 2014);
INSERT INTO `ekspor` (`Berat/Weight (KG)`, `Bulan/Month`, `Nilai/Value (US $)`, `Tahun`)
    VALUES
        (4.344319503504E10, 'Januari/January', 1.324487679753E10, 2015);
INSERT INTO `ekspor` (`Berat/Weight (KG)`, `Bulan/Month`, `Nilai/Value (US $)`, `Tahun`)
    VALUES
        (3.976834267662E10, 'Pebruari/February', 1.217280286267E10, 2015);
INSERT INTO `ekspor` (`Berat/Weight (KG)`, `Bulan/Month`, `Nilai/Value (US $)`, `Tahun`)
    VALUES
        (4.820923134305E10, 'Maret/March', 1.363404196514E10, 2015);
INSERT INTO `ekspor` (`Berat/Weight (KG)`, `Bulan/Month`, `Nilai/Value (US $)`, `Tahun`)
    VALUES
        (4.411316714817E10, 'April/April', 1.310459680438E10, 2015);
INSERT INTO `ekspor` (`Berat/Weight (KG)`, `Bulan/Month`, `Nilai/Value (US $)`, `Tahun`)
    VALUES
        (4.154364405926E10, 'Mei/May', 1.275465904369E10, 2015);
INSERT INTO `ekspor` (`Berat/Weight (KG)`, `Bulan/Month`, `Nilai/Value (US $)`, `Tahun`)
    VALUES
        (4.088655495092E10, 'Juni/June', 1.351410187906E10, 2015);
INSERT INTO `ekspor` (`Berat/Weight (KG)`, `Bulan/Month`, `Nilai/Value (US $)`, `Tahun`)
    VALUES
        (4.090871175463E10, 'Juli/July', 1.146577976441E10, 2015);
INSERT INTO `ekspor` (`Berat/Weight (KG)`, `Bulan/Month`, `Nilai/Value (US $)`, `Tahun`)
    VALUES
        (4.170396214789E10, 'Agustus/August', 1.272603750673E10, 2015);
INSERT INTO `ekspor` (`Berat/Weight (KG)`, `Bulan/Month`, `Nilai/Value (US $)`, `Tahun`)
    VALUES
        (4.113072793385E10, 'September/September', 1.25883593707E10, 2015);
INSERT INTO `ekspor` (`Berat/Weight (KG)`, `Bulan/Month`, `Nilai/Value (US $)`, `Tahun`)
    VALUES
        (4.349232467564E10, 'Oktober/October', 1.21217405723E10, 2015);
INSERT INTO `ekspor` (`Berat/Weight (KG)`, `Bulan/Month`, `Nilai/Value (US $)`, `Tahun`)
    VALUES
        (4.157222267935E10, 'Nopember/November', 1.112218255429E10, 2015);
INSERT INTO `ekspor` (`Berat/Weight (KG)`, `Bulan/Month`, `Nilai/Value (US $)`, `Tahun`)
    VALUES
        (4.288968022137E10, 'Desember/December', 1.191711238167E10, 2015);
INSERT INTO `ekspor` (`Berat/Weight (KG)`, `Bulan/Month`, `Nilai/Value (US $)`, `Tahun`)
    VALUES
        (3.959348016023E10, 'Januari/January', 1.058188383798E10, 2016);
INSERT INTO `ekspor` (`Berat/Weight (KG)`, `Bulan/Month`, `Nilai/Value (US $)`, `Tahun`)
    VALUES
        (3.869917612586E10, 'Pebruari/February', 1.131673418851E10, 2016);
INSERT INTO `ekspor` (`Berat/Weight (KG)`, `Bulan/Month`, `Nilai/Value (US $)`, `Tahun`)
    VALUES
        (4.302904963314E10, 'Maret/March', 1.181212747793E10, 2016);
INSERT INTO `ekspor` (`Berat/Weight (KG)`, `Bulan/Month`, `Nilai/Value (US $)`, `Tahun`)
    VALUES
        (3.955838186875E10, 'April/April', 1.168974585103E10, 2016);
INSERT INTO `ekspor` (`Berat/Weight (KG)`, `Bulan/Month`, `Nilai/Value (US $)`, `Tahun`)
    VALUES
        (4.062240624097E10, 'Mei/May', 1.151740912588E10, 2016);
INSERT INTO `ekspor` (`Berat/Weight (KG)`, `Bulan/Month`, `Nilai/Value (US $)`, `Tahun`)
    VALUES
        (4.476689458467E10, 'Juni/June', 1.320612276522E10, 2016);
INSERT INTO `ekspor` (`Berat/Weight (KG)`, `Bulan/Month`, `Nilai/Value (US $)`, `Tahun`)
    VALUES
        (3.903204698871E10, 'Juli/July', 9.64950397597E9, 2016);
INSERT INTO `ekspor` (`Berat/Weight (KG)`, `Bulan/Month`, `Nilai/Value (US $)`, `Tahun`)
    VALUES
        (4.580057679174E10, 'Agustus/August', 1.275392132113E10, 2016);
INSERT INTO `ekspor` (`Berat/Weight (KG)`, `Bulan/Month`, `Nilai/Value (US $)`, `Tahun`)
    VALUES
        (4.414627167066E10, 'September/September', 1.257975024995E10, 2016);
INSERT INTO `ekspor` (`Berat/Weight (KG)`, `Bulan/Month`, `Nilai/Value (US $)`, `Tahun`)
    VALUES
        (4.737838467157E10, 'Oktober/October', 1.274373688372E10, 2016);
INSERT INTO `ekspor` (`Berat/Weight (KG)`, `Bulan/Month`, `Nilai/Value (US $)`, `Tahun`)
    VALUES
        (4.660620608796E10, 'Nopember/November', 1.350292038269E10, 2016);
INSERT INTO `ekspor` (`Berat/Weight (KG)`, `Bulan/Month`, `Nilai/Value (US $)`, `Tahun`)
    VALUES
        (4.555170074795E10, 'Desember/December', 1.383235518641E10, 2016);
INSERT INTO `ekspor` (`Berat/Weight (KG)`, `Bulan/Month`, `Nilai/Value (US $)`, `Tahun`)
    VALUES
        (4.356598997433E10, 'Januari/January', 1.339767658781E10, 2017);
INSERT INTO `ekspor` (`Berat/Weight (KG)`, `Bulan/Month`, `Nilai/Value (US $)`, `Tahun`)
    VALUES
        (3.746781272218E10, 'Pebruari/February', 1.261598031509E10, 2017);
INSERT INTO `ekspor` (`Berat/Weight (KG)`, `Bulan/Month`, `Nilai/Value (US $)`, `Tahun`)
    VALUES
        (4.777691374186E10, 'Maret/March', 1.471847768689E10, 2017);
INSERT INTO `ekspor` (`Berat/Weight (KG)`, `Bulan/Month`, `Nilai/Value (US $)`, `Tahun`)
    VALUES
        (4.424856528056E10, 'April/April', 1.326968961758E10, 2017);
INSERT INTO `ekspor` (`Berat/Weight (KG)`, `Bulan/Month`, `Nilai/Value (US $)`, `Tahun`)
    VALUES
        (4.404970022686E10, 'Mei/May', 1.433385952355E10, 2017);
INSERT INTO `ekspor` (`Berat/Weight (KG)`, `Bulan/Month`, `Nilai/Value (US $)`, `Tahun`)
    VALUES
        (3.98991235473E10, 'Juni/June', 1.166137638086E10, 2017);
INSERT INTO `ekspor` (`Berat/Weight (KG)`, `Bulan/Month`, `Nilai/Value (US $)`, `Tahun`)
    VALUES
        (4.510408646225E10, 'Juli/July', 1.361106249927E10, 2017);
INSERT INTO `ekspor` (`Berat/Weight (KG)`, `Bulan/Month`, `Nilai/Value (US $)`, `Tahun`)
    VALUES
        (4.760385932686E10, 'Agustus/August', 1.518799099689E10, 2017);
INSERT INTO `ekspor` (`Berat/Weight (KG)`, `Bulan/Month`, `Nilai/Value (US $)`, `Tahun`)
    VALUES
        (4.828945139564E10, 'September/September', 1.45802161118E10, 2017);
INSERT INTO `ekspor` (`Berat/Weight (KG)`, `Bulan/Month`, `Nilai/Value (US $)`, `Tahun`)
    VALUES
        (5.082082819165E10, 'Oktober/October', 1.525256352606E10, 2017);
INSERT INTO `ekspor` (`Berat/Weight (KG)`, `Bulan/Month`, `Nilai/Value (US $)`, `Tahun`)
    VALUES
        (4.790595532527E10, 'Nopember/November', 1.533473560061E10, 2017);
INSERT INTO `ekspor` (`Berat/Weight (KG)`, `Bulan/Month`, `Nilai/Value (US $)`, `Tahun`)
    VALUES
        (4.911434686232E10, 'Desember/December', 1.486454708961E10, 2017);
INSERT INTO `ekspor` (`Berat/Weight (KG)`, `Bulan/Month`, `Nilai/Value (US $)`, `Tahun`)
    VALUES
        (4.820718845641E10, 'Januari/January', 1.457627732578E10, 2018);
INSERT INTO `ekspor` (`Berat/Weight (KG)`, `Bulan/Month`, `Nilai/Value (US $)`, `Tahun`)
    VALUES
        (4.603528223381E10, 'Pebruari/February', 1.413238205593E10, 2018);
INSERT INTO `ekspor` (`Berat/Weight (KG)`, `Bulan/Month`, `Nilai/Value (US $)`, `Tahun`)
    VALUES
        (5.207825956993E10, 'Maret/March', 1.551061670318E10, 2018);
INSERT INTO `ekspor` (`Berat/Weight (KG)`, `Bulan/Month`, `Nilai/Value (US $)`, `Tahun`)
    VALUES
        (4.73867673064E10, 'April/April', 1.449623805747E10, 2018);
INSERT INTO `ekspor` (`Berat/Weight (KG)`, `Bulan/Month`, `Nilai/Value (US $)`, `Tahun`)
    VALUES
        (5.157756377248E10, 'Mei/May', 1.619834082626E10, 2018);
INSERT INTO `ekspor` (`Berat/Weight (KG)`, `Bulan/Month`, `Nilai/Value (US $)`, `Tahun`)
    VALUES
        (4.952218174715E10, 'Juni/June', 1.294173983172E10, 2018);
INSERT INTO `ekspor` (`Berat/Weight (KG)`, `Bulan/Month`, `Nilai/Value (US $)`, `Tahun`)
    VALUES
        (5.444126818418E10, 'Juli/July', 1.628471999231E10, 2018);
INSERT INTO `ekspor` (`Berat/Weight (KG)`, `Bulan/Month`, `Nilai/Value (US $)`, `Tahun`)
    VALUES
        (4.86194067226E10, 'Agustus/August', 1.586512405642E10, 2018);
INSERT INTO `ekspor` (`Berat/Weight (KG)`, `Bulan/Month`, `Nilai/Value (US $)`, `Tahun`)
    VALUES
        (5.039303287386E10, 'September/September', 1.495634823423E10, 2018);
INSERT INTO `ekspor` (`Berat/Weight (KG)`, `Bulan/Month`, `Nilai/Value (US $)`, `Tahun`)
    VALUES
        (5.67065111815E10, 'Oktober/October', 1.590907284628E10, 2018);
INSERT INTO `ekspor` (`Berat/Weight (KG)`, `Bulan/Month`, `Nilai/Value (US $)`, `Tahun`)
    VALUES
        (5.11413211568E10, 'Nopember/November', 1.485172086222E10, 2018);
INSERT INTO `ekspor` (`Berat/Weight (KG)`, `Bulan/Month`, `Nilai/Value (US $)`, `Tahun`)
    VALUES
        (5.279873601076E10, 'Desember/December', 1.429009321017E10, 2018);
